version: '3.0'
services:
  app1:
    image: waabuffet/devops-voting-app
    container_name: devops_app1
    # ports:
    #   - $APP1_PORT:80
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - WORKDIR=$APP_WORKDIR
  app2:
    image: waabuffet/devops-voting-app
    container_name: devops_app2
    # ports:
    #   - $APP2_PORT:80
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - WORKDIR=$APP_WORKDIR
  haproxy:
    image: haproxy
    container_name: devops_haproxy
    ports:
      - 8080:80
    volumes:
      - $HAPROXY_CONF:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
  db:
    image: mysql:latest
    container_name: $DB_HOST
    volumes:
      - $DB_DATA:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
