apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-voting-app.fullname" . }}
  labels:
    {{- include "devops-voting-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      # nodePort: 30000
  selector:
    app: {{ include "devops-voting-app.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
spec:
  selector: 
    app: {{ .Values.database.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: 3306