apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: voting-app
  labels:
    app: voting-app
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voting-app
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  # behavior:
  #   scaleDown:
  #     stabilizationWindowSeconds: 3
  #     policies:
  #     - type: Percent
  #       value: 100
  #       periodSeconds: 5
  #   scaleUp:
  #     stabilizationWindowSeconds: 3
  #     policies:
  #     - type: Percent
  #       value: 50
  #       periodSeconds: 3
  #     # - type: Pods
  #     #   value: 1
  #     #   periodSeconds: 5
  #     selectPolicy: Max