apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: voting-app
        image: waabuffet/devops-voting-app
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 400m
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: voting-app-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: voting-app-config
                key: DB_PORT
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: voting-app-config
                key: DB_DATABASE
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: voting-app-config
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASS
          - name: WORKDIR
            valueFrom:
              configMapKeyRef:
                name: voting-app-config
                key: APP_WORKDIR
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
spec:
  selector: 
    app: voting-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
      nodePort: 30000